<?php

namespace App\Support;

abstract class Translate
{
    CONST PT_BR = [
        'id'              => 'id',
        'name'            => 'nome',
        'social_reason'   => 'razão social',
        'cpf'             => 'cpf',
        'cnpj'            => 'cnpj',
        'rg'              => 'rg',
        'street'          => 'rua',
        'neighborhood'    => 'bairro',
        'number'          => 'número',
        'complement'      => 'complemento',
        'zipcode'         => 'cep',
        'logo'            => 'logo',
        'avatar'          => 'avatar',
        'email'           => 'email',
        'is_active'       => 'ativo',
        'password'        => 'senha',
        'last_access'     => 'último acesso',
        'title'           => 'título',
        'body'            => 'corpo',
        'observation'     => 'observation',
        'description'     => 'descrição',
        'contact_type_id' => 'tipo de contato',
        'company_id'      => 'empresa',
        'client_id'       => 'cliente',
        'user_id'         => 'usuário',
        'schedule_id'     => 'agendamento',
        'appointment_id'  => 'compromisso',
        'key'             => 'chave',
        'value'           => 'valor',
        'payment_type'    => 'tipo de pagamento',
        'notes'           => 'notas',
        'status'          => 'status',
        'start_at'        => 'inicia em',
        'finish_at'       => 'finaliza em',
        'repeat_days'     => 'dias em que se repetem',
        'exercise'        => 'Exercício',
        'sex'=>'Sexo',
        'blood_type'      => 'Tipo Sanguíneo',
        'phone' => 'Telefone',
        'birthday' => 'Aniversário',
        'city_id' => 'Cidade',
        'neck' => 'Pescoço',
        'shoulder' => 'Ombros',
        'chest' => 'Peito',
        'right_arm' => 'Braço Direito',
        'left_arm' => 'Braço Esquerdo',
        'right_forearm' => 'Antebraço Direito',
        'left_forearm' => 'Antebraço Esquerdo',
        'waist' => 'Cintura',
        'abdomen' => 'Abdomem',
        'hip' => 'Quadril',
        'right_thigh' => 'Coxa Direita',
        'left_thigh' => 'Coxa Esquerda',
        'right_calf' => 'Panturrilha Direita',
        'left_calf' => 'Panturrilha Esquerda',
        'height' => 'Altura',
        'weight' => 'Peso',
        'blood_pressure' => 'Pressão Sanguínea'


    ];
}
