<?php

namespace App\Repositories;


use App\Models\Client;
use App\Models\Company;
use App\Models\User;
use App\Repositories\Contracts\UserRepository;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class EloquentUserRepository extends AbstractEloquentRepository implements UserRepository
{
    public function getExtraData()
    {
        return [
            'client' => Client::all(),
            'company' => Company::all(),
            'role' => Role::all(),
        ];
    }

    public function save(array $data)
    {
        $user = User::create([
            'name'       => $data['name'],
            'email'      => $data['email'],
            'password'   => Hash::make($data['password']),
            'client_id'  => $data['client_id'],
            'company_id' => $data['company_id']
        ]);
        $user->assignRole($data['role_name']);

        return $user;
//        return parent::save($data); // TODO: Change the autogenerated stub
    }

    public function update(Model $model, array $data)
    {
        return parent::update($model, $data); // TODO: Change the autogenerated stub
    }

    public function delete(Model $model)
    {
        return parent::delete($model);
    }
}
