<?php

namespace App\Repositories;


use App\Models\Back;
use App\Models\BackWorkout;
use App\Models\Biceps;
use App\Models\BicepsWorkout;
use App\Models\Breast;
use App\Models\BreastWorkout;
use App\Models\Client;
use App\Models\LowerMember;
use App\Models\LowerMemberWorkout;
use App\Models\Shoulder;
use App\Models\ShoulderWorkout;
use App\Models\Triceps;
use App\Models\TricepsWorkout;
use App\Models\Workout;
use App\Repositories\Contracts\WorkoutRepository;
use Illuminate\Database\Eloquent\Model;

class EloquentWorkoutRepository extends AbstractEloquentRepository implements WorkoutRepository
{

    public function save(array $data)
    {
        return parent::save($data); // TODO: Change the autogenerated stub
    }

    public function update(Model $model, array $data)
    {
        return parent::update($model, $data); // TODO: Change the autogenerated stub
    }

    public function delete(Model $model)
    {
        return parent::delete($model);
    }

    public function getExerciciosTreino($id)
    {
        $data = Workout::find($id);
        $data['triceps_treino'] = TricepsWorkout::where('id_treino', $data['id'])->get();
        $data['biceps_treino'] = BicepsWorkout::where('id_treino', $data['id'])->get();
        $data['costa_treino'] = BackWorkout::where('id_treino', $data['id'])->get();
        $data['ombro_treino'] = ShoulderWorkout::where('id_treino', $data['id'])->get();
        $data['peitoral_treino'] = BreastWorkout::where('id_treino', $data['id'])->get();
        $data['membro_inferior_treino'] = LowerMemberWorkout::where('id_treino', $data['id'])->get();
        return $data;
    }

    public function getExtraData()
    {
        return [
            'client'          => Client::all(),
            'biceps'          => Biceps::all(),
            'triceps'         => Triceps::all(),
            'back'            => Back::all(),
            'breast'          => Breast::all(),
            'shoulder'        => Shoulder::all(),
            'membro_inferior' => LowerMember::all()
        ];
    }

    public function save_triceps_treino($data)
    {
        TricepsWorkout::create([
            'id_treino'  => $data['id_treino'],
            'id_triceps' => $data['id_triceps']
        ]);
    }

    public function update_triceps_treino($data)
    {
        TricepsWorkout::
        where('id_treino', $data['id_treino'])
            ->where('id_triceps', $data['id_triceps'])
            ->update([
                'kg'    => $data['kg'],
                'serie' => $data['serie'],
                'rep'   => $data['rep'],
                'grupo' => $data['grupo']
            ]);
    }

    public function save_biceps_treino($data)
    {
        BicepsWorkout::create([
            'id_treino' => $data['id_treino'],
            'id_biceps' => $data['id_biceps']
        ]);
    }

    public function update_biceps_treino($data)
    {
        BicepsWorkout::
        where('id_treino', $data['id_treino'])
            ->where('id_biceps', $data['id_biceps'])
            ->update([
                'kg'    => $data['kg'],
                'serie' => $data['serie'],
                'rep'   => $data['rep'],
                'grupo' => $data['grupo']
            ]);
    }

    public function save_costa_treino($data)
    {
        BackWorkout::create([
            'id_treino' => $data['id_treino'],
            'id_costa'  => $data['id_costa']
        ]);
    }

    public function update_costa_treino($data)
    {
        BackWorkout::
        where('id_treino', $data['id_treino'])
            ->where('id_costa', $data['id_costa'])
            ->update([
                'kg'    => $data['kg'],
                'serie' => $data['serie'],
                'rep'   => $data['rep'],
                'grupo' => $data['grupo']
            ]);
    }

    public function save_peitoral_treino($data)
    {
        BreastWorkout::create([
            'id_treino'   => $data['id_treino'],
            'id_peitoral' => $data['id_peitoral']
        ]);
    }

    public function update_peitoral_treino($data)
    {
        BreastWorkout::
        where('id_treino', $data['id_treino'])
            ->where('id_peitoral', $data['id_peitoral'])
            ->update([
                'kg'    => $data['kg'],
                'serie' => $data['serie'],
                'rep'   => $data['rep'],
                'grupo' => $data['grupo']
            ]);
    }

    public function save_ombro_treino($data)
    {
        ShoulderWorkout::create([
            'id_treino' => $data['id_treino'],
            'id_ombro'  => $data['id_ombro']
        ]);
    }

    public function update_ombro_treino($data)
    {
        ShoulderWorkout::
        where('id_treino', $data['id_treino'])
            ->where('id_ombro', $data['id_ombro'])
            ->update([
                'kg'    => $data['kg'],
                'serie' => $data['serie'],
                'rep'   => $data['rep'],
                'grupo' => $data['grupo']
            ]);
    }

    public function save_membro_inferior_treino($data)
    {
        LowerMemberWorkout::create([
            'id_treino'          => $data['id_treino'],
            'id_membro_inferior' => $data['id_membro_inferior']
        ]);
    }

    public function update_membro_inferior_treino($data)
    {
        LowerMemberWorkout::
        where('id_treino', $data['id_treino'])
            ->where('id_membro_inferior', $data['id_membro_inferior'])
            ->update([
                'kg'    => $data['kg'],
                'serie' => $data['serie'],
                'rep'   => $data['rep'],
                'grupo' => $data['grupo']
            ]);
    }


}
