<?php

namespace App\Repositories;


use App\Models\Back;
use App\Models\BackWorkout;
use App\Models\Biceps;
use App\Models\BicepsWorkout;
use App\Models\Breast;
use App\Models\BreastWorkout;
use App\Models\Client;
use App\Models\LowerMember;
use App\Models\LowerMemberWorkout;
use App\Models\Shoulder;
use App\Models\ShoulderWorkout;
use App\Models\Triceps;
use App\Models\TricepsWorkout;
use App\Models\Workout;
use App\Repositories\Contracts\WorkoutRepository;
use Illuminate\Database\Eloquent\Model;

class EloquentWorkoutRepository extends AbstractEloquentRepository implements WorkoutRepository
{

    public function save(array $data)
    {
        return parent::save($data); // TODO: Change the autogenerated stub
    }

    public function update(Model $model, array $data)
    {
        return parent::update($model, $data); // TODO: Change the autogenerated stub
    }

    public function delete(Model $model)
    {
        return parent::delete($model);
    }

    public function getExerciciosTreino($id)
    {
        $data = Workout::find($id);
        $data['triceps_workout'] = TricepsWorkout::where('id_workout', $data['id'])->get();
        $data['biceps_workout'] = BicepsWorkout::where('id_workout', $data['id'])->get();
        $data['back_workout'] = BackWorkout::where('id_workout', $data['id'])->get();
        $data['shoulder_workout'] = ShoulderWorkout::where('id_workout', $data['id'])->get();
        $data['breast_workout'] = BreastWorkout::where('id_workout', $data['id'])->get();
        $data['lower_member_workout'] = LowerMemberWorkout::where('id_workout', $data['id'])->get();
        return $data;
    }

    public function getExtraData()
    {
        return [
            'client'       => Client::all(),
            'biceps'       => Biceps::all(),
            'triceps'      => Triceps::all(),
            'back'         => Back::all(),
            'breast'       => Breast::all(),
            'shoulder'     => Shoulder::all(),
            'lower_member' => LowerMember::all()
        ];
    }

    public function save_triceps_workout($data)
    {
        TricepsWorkout::create([
            'id_workout' => $data['id_workout'],
            'id_triceps' => $data['id_triceps']
        ]);
    }

    public function update_triceps_workout($data)
    {
        TricepsWorkout::
        where('id_workout', $data['id_workout'])
            ->where('id_triceps', $data['id_triceps'])
            ->update([
                'kg'    => $data['kg'],
                'serie' => $data['serie'],
                'rep'   => $data['rep'],
                'grupo' => $data['grupo']
            ]);
    }

    public function save_biceps_workout($data)
    {
        BicepsWorkout::create([
            'id_workout' => $data['id_workout'],
            'id_biceps'  => $data['id_biceps']
        ]);
    }

    public function update_biceps_workout($data)
    {
        BicepsWorkout::
        where('id_workout', $data['id_workout'])
            ->where('id_biceps', $data['id_biceps'])
            ->update([
                'kg'    => $data['kg'],
                'serie' => $data['serie'],
                'rep'   => $data['rep'],
                'grupo' => $data['grupo']
            ]);
    }

    public function save_back_workout($data)
    {
        BackWorkout::create([
            'id_workout' => $data['id_workout'],
            'id_back'    => $data['id_back']
        ]);
    }

    public function update_back_workout($data)
    {
        BackWorkout::
        where('id_workout', $data['id_workout'])
            ->where('id_back', $data['id_back'])
            ->update([
                'kg'    => $data['kg'],
                'serie' => $data['serie'],
                'rep'   => $data['rep'],
                'grupo' => $data['grupo']
            ]);
    }

    public function save_breast_workout($data)
    {
        BreastWorkout::create([
            'id_workout' => $data['id_workout'],
            'id_breast'  => $data['id_breast']
        ]);
    }

    public function update_breast_workout($data)
    {
        BreastWorkout::
        where('id_workout', $data['id_workout'])
            ->where('id_breast', $data['id_breast'])
            ->update([
                'kg'    => $data['kg'],
                'serie' => $data['serie'],
                'rep'   => $data['rep'],
                'grupo' => $data['grupo']
            ]);
    }

    public function save_shoulder_workout($data)
    {
        ShoulderWorkout::create([
            'id_workout'  => $data['id_workout'],
            'id_shoulder' => $data['id_shoulder']
        ]);
    }

    public function update_shoulder_workout($data)
    {
        ShoulderWorkout::
        where('id_workout', $data['id_workout'])
            ->where('id_shoulder', $data['id_shoulder'])
            ->update([
                'kg'    => $data['kg'],
                'serie' => $data['serie'],
                'rep'   => $data['rep'],
                'grupo' => $data['grupo']
            ]);
    }

    public function save_lower_member_workout($data)
    {
        LowerMemberWorkout::create([
            'id_workout'      => $data['id_workout'],
            'id_lower_member' => $data['id_lower_member']
        ]);
    }

    public function update_lower_member_workout($data)
    {
        LowerMemberWorkout::
        where('id_workout', $data['id_workout'])
            ->where('id_lower_member', $data['id_lower_member'])
            ->update([
                'kg'    => $data['kg'],
                'serie' => $data['serie'],
                'rep'   => $data['rep'],
                'grupo' => $data['grupo']
            ]);
    }


}
