<?php

namespace App\Repositories;

use App\Models\BackWorkout;
use App\Models\BicepsWorkout;
use App\Models\BreastWorkout;
use App\Models\LowerMemberWorkout;
use App\Models\ShoulderWorkout;
use App\Models\TricepsWorkout;
use App\Models\Workout;
use App\Repositories\Contracts\ClientRepository;
use Illuminate\Database\Eloquent\Model;

class EloquentClientRepository extends AbstractEloquentRepository implements ClientRepository
{

    public function save(array $data)
    {
        return parent::save($data); // TODO: Change the autogenerated stub
    }

    public function saveConfiguracaoCliente(array $data)
    {
        ConfiguracaoCliente::create($data); // TODO: Change the autogenerated stub
    }

    public function updateConfiguracaoCliente(array $data)
    {

        $configuracao = ConfiguracaoCliente::where('id_cliente', $data['id_cliente'])->first();
        if ($configuracao) {

            return $configuracao->update([
                'formula'     => $data['formula'],
                'porcentagem' => $data['porcentagem']
            ]);
        } else {

            ConfiguracaoCliente::create($data); // TODO: Change the autogenerated stub
        }
    }

    public function update(Model $model, array $data)
    {
        return parent::update($model, $data); // TODO: Change the autogenerated stub
    }

    public function delete(Model $model)
    {
        return parent::delete($model);
    }

    public function getExerciciosTreino($id)
    {
        $data = Workout::find($id);
        $data['triceps_workout'] = TricepsWorkout::where('id_workout', $id)->get();
        $data['biceps_workout'] = BicepsWorkout::where('id_workout', $id)->get();
        $data['back_workout'] = BackWorkout::where('id_workout', $id)->get();
        $data['shoulder_workout'] = ShoulderWorkout::where('id_workout', $id)->get();
        $data['breast_workout'] = BreastWorkout::where('id_workout', $id)->get();
        $data['lower_member_workout'] = LowerMemberWorkout::where('id_workout', $id)->get();
        return $data;
    }
}
